### ISSUE TITLE
Couldn't run multischool

### ISSUE THREAD

**Issue by snehithlal** [ahammednafih/dockerize-fedena#1]
@ahammednafih  

trace:

fedena git:(verified) ✗ docker-compose exec web rake fedena:install_multischool RAILS_ENV=production

==  ChangeArchivedEmployee: migrating =========================================
-- change_column(:archived_employees, :gender, :string)
   -> 0.0391s
==  ChangeArchivedEmployee: migrated (0.0391s) ================================

rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Duplicate entry '20121130114907' for key 'unique_schema_migrations': INSERT INTO schema_migrations (version) VALUES ('20121130114907')/usr/local/bundle/bundler/gems/rails-c6c5ad39cc16/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:227:in `rescue in log'
/usr/local/bundle/bundler/gems/rails-c6c5ad39cc16/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:203:in `log'

**Comment by ahammednafih** [comment]
@snehithlal Is it running fine when we run `docket-compose up`?

**Comment by snehithlal** [comment]
Yes. I will record the video and post it here.

**Comment by snehithlal** [comment]
@ahammednafih https://vimeo.com/713232746/0187b54fa5

up also failing

`fedena_db   | Version: '10.8.3-MariaDB-1:10.8.3+maria~jammy'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
fedena_app  | rake aborted!
fedena_app  | Mysql2::Error: Unknown database 'fedena'
fedena_app  | /usr/local/bundle/gems/mysql2-0.2.24/lib/mysql2/client.rb:70:in `connect'
fedena_app  | /usr/local/bundle/gems/mysql2-0.2.24/lib/mysql2/client.rb:70:in `initialize'
fedena_app  | /usr/local/bundle/gems/mysql2-0.2.24/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `new'
fedena_app  | /usr/local/bundle/gems/mysql2-0.2.24/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `mysql2_connection'
fedena_app  | /usr/local/bundle/bundler/gems/rails-c6c5ad39cc16/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:223:in `new_connection'`
